version: '3.4'

services:
  productservice:
    container_name: productservice
    environment:
      - OPSConnectionString=Data Source=octopetshop.czackpbhxo2c.us-east-1.rds.amazonaws.com;Initial Catalog=OctoPetShop; User ID=admin; Password=OctopusDeploy_1234
    image: octopustestaccount/octopetshop-productservice
    networks:
      - octonet

  shoppingcartservice:
    container_name: shoppingcartservice
    image: octopustestaccount/octopetshop-shoppingcartservice
    environment:
      - OPSConnectionString=Data Source=octopetshop.czackpbhxo2c.us-east-1.rds.amazonaws.com;Initial Catalog=OctoPetShop; User ID=admin; Password=OctopusDeploy_1234
    networks:
      - octonet

  web:
    container_name: web
    image: octopustestaccount/octopetshop-web
    environment:
      - ProductServiceBaseUrl=http://productservice
      - ShoppingCartServiceBaseUrl=http://shoppingcartservice
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - "shoppingcartservice"
      - "productservice"
    networks:
      - octonet

#  database:
#    container_name: database
#    environment:
#      - DbUpConnectionString=Data Source=octopetshop.czackpbhxo2c.us-east-1.rds.amazonaws.com;Initial Catalog=OctoPetShop; User ID=admin; Password=OctopusDeploy_1234
#    image: octopustestaccount/octopetshop-database
#    networks:
#      - octonet

networks:
  octonet:
